
name: Publish to BCR

# this is just a test to create a module entry into BCR, not for any real world use
  
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'tag'
        required: true
        default: 'v1.0.0'
      bcr:
        description: 'bazel central registry target'
        required: true
        default: 'loosebazooka/bazel-central-registry'
      git_email:
        description: 'to use for git commits'
        required: true
        default: 'appu@google.com'
      git_name:
        description: 'to use for git commits'
        required: true
        default: 'Appu Goundan'
      github_name:
        description: 'owner of module'
        required: true
        default: 'loosebazooka'
        

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Set env
      run: |
        echo "TAG=${{ github.event.inputs.tag }}" >> $GITHUB_ENV
        echo "REPO=${{ github.event.repository.name }}" >> $GITHUB_ENV
        echo "OWNER=${{ github.repository_owner }}" >> $GITHUB_ENV
        echo "BCR=${{ github.event.inputs.bcr }}" >> $GITHUB_ENV

    - name: Checkout this repo
      uses: actions/checkout@v4.2.2
      with:
        path: 'this'

    - name: Checkout BCR
      uses: actions/checkout@v4.2.2
      with:
        repository: ${{ env.BCR }}
        token: ${{ secrets.BCR_FORK_WRITE_TOKEN }}
        path: 'bcr'
      
    - name: Read release Info
      env:
        GH_TOKEN: ${{ github.token }}
        GIT_EMAIL: ${{ github.event.inputs.git_email }}
        GIT_NAME: ${{ github.event.inputs.git_name }}
        GITHUB_NAME: ${{ github.event.inputs.github_name }}
        HOME: ${{ github.workspace }}
      run: |
        set -o errexit -o nounset -o pipefail -o xtrace
        export VERSION=${TAG:1}
        cd bcr
        mkdir -p modules/${REPO}/${VERSION}
        cd modules/${REPO}
        
        if [ ! -f ./metadata.json ]; then
          envsubst < $HOME/this/.templates/metadata.json.template > metadata.json
        fi
        
        jq --arg VERSION $VERSION '.versions += [$VERSION]' metadata.json > metadata.json.new; mv metadata.json.new metadata.json
        gh release view $TAG -R $OWNER/$REPO --json assets --jq '.assets.[].url' | grep -v .intoto.jsonl | grep -v .tar.gz | xargs wget -q
        export BRANCH=add_${REPO}_${VERSION}_$(date +%s)

        git status
        
        git config --global user.email "${GIT_EMAIL}"
        git config --global user.name "${GIT_NAME}"
        
        git checkout -b $BRANCH
        git add .
        git commit -m "add $VERSION for $REPO"
        git push origin $BRANCH
