
name: Create Test Module

# this is just a test to create a module entry into BCR, not for any real world use
  
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'tag'
        required: true
        default: 'v1.0.0'
      bcr:
        description: 'bazel central registry target'
        required: true
        default: 'loosebazooka/bazel-central-registry'
      git_email:
        description: 'to use for git commits'
        required: true
        default: 'appu@google.com'
      git_name:
        description: 'to use for git commits'
        required: true
        default: 'Appu Goundan'

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Set env
      run: |
        echo "TAG=${{ github.event.inputs.tag }}" >> $GITHUB_ENV
        echo "REPO=${{ github.event.repository.name }}" >> $GITHUB_ENV
        echo "ORG=${{ github.repository_owner }}" >> $GITHUB_ENV
        echo "BCR=${{ github.event.inputs.bcr }}" >> $GITHUB_ENV

    - name: Checkout
      uses: actions/checkout@v4.2.2
      with:
        repository: ${{ env.BCR }}
      
    - name: Read release Info
      env:
        GH_TOKEN: ${{ github.token }}
        GIT_EMAIL: ${{ github.event.inputs.git_email }}
        GIT_NAME: ${{ github.event.inputs.git_name }}
      run: |
        set -o errexit -o nounset -o pipefail -o xtrace
        export VERSION=${TAG:1}
        mkdir -p modules/${REPO}/${VERSION}
        cd modules/${REPO}
        jq --arg VERSION $VERSION '.versions += [$VERSION]' metadata.json > metadata.json.new; mv metadata.json.new metadata.json
        gh release view $TAG -R $ORG/$REPO --json assets --jq '.assets.[].url' | grep -v .intoto.jsonl | grep -v .tar.gz | xargs wget -q
        export BRANCH=add_${REPO}_${VERSION}
        
        git config --global user.email "${GIT_EMAIL}"
        git config --global user.name "${GIT_NAME}"
        
        git checkout -b $BRANCH
        git commit -a -m "add $VERSION for $REPO"
        git push origin $BRANCH
