name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  archive-and-attest:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      attestations: write
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Set env
      run: |
        echo "TAG=${GITHUB_REF_NAME}" >> $GITHUB_ENV
        echo "VERSION=${GITHUB_REF_NAME:1}" >> $GITHUB_ENV
        echo "ARCHIVE=bcr-module-provenance-${GITHUB_REF_NAME}.tar.gz" >> $GITHUB_ENV
        echo "PREFIX=bcr-module-provenance-${GITHUB_REF_NAME:1}" >> $GITHUB_ENV
        echo "REPO=${{ github.event.repository.name }}" >> $GITHUB_ENV
        echo "ORG=${{ github.repository_owner }}" >> $GITHUB_ENV

    # really this should all be coming from https://github.com/bazel-contrib/.github/blob/master/.github/workflows/release_ruleset.yaml
    # but we just do this super janky here for this example
    - name: Archive
      run: |
        set -o errexit -o nounset -o pipefail
        git archive --format=tar --prefix=${PREFIX}/ ${TAG} | gzip > $ARCHIVE
        echo "SHA_256=sha256-$(sha256sum $ARCHIVE | awk '{print $1}' | xxd -r -p | base64)" >> $GITHUB_ENV

    - name: Create module metadata
      run: |
        envsubst < .templates/source.json.template > source.json
    # MODULE.bazel is already in root, so we don't need to copy it over in this example
    
    - name: Upload release stuff
      uses: actions/upload-artifact@v4
      with:
        path: |
          ${{ env.ARCHIVE }}
          source.json
          MODULE.bazel

    - name: Attest Source Archive Provenance
      id: attest_source_archive
      uses: actions/attest-build-provenance@v2
      with:
        subject-path: ${{ env.ARCHIVE }}

    - name: Write Source Archive Provenance into intoto.jsonl
      run: |
        cat ${{ steps.attest_source_archive.outputs.bundle-path }} | jq -c > ${{ env.ARCHIVE }}.intoto.jsonl
        echo "ATT_SHA_256=sha256-$(sha256sum $ARCHIVE | awk '{print $1}' | xxd -r -p | base64)" >> $GITHUB_ENV

    - name: Attest source.json Provenance
      id: attest_source_json
      uses: actions/attest-build-provenance@v2
      with:
        subject-path: source.json
    
    - name: Write source.json Provenance into intoto.jsonl
      run: |
        cat ${{ steps.attest_source_json.outputs.bundle-path }} | jq -c > source.json.intoto.jsonl
        echo "SOURCE_JSON_ATT_SHA_256=sha256-$(sha256sum source.json.intoto.jsonl | awk '{print $1}' | xxd -r -p | base64)" >> $GITHUB_ENV

    - name: Attest MODULE.bazel Provenance
      id: attest_module_bazel
      uses: actions/attest-build-provenance@v2
      with:
        subject-path: MODULE.bazel

    - name: Write source.json Provenance into intoto.jsonl
      run: |
        cat ${{ steps.attest_module_bazel.outputs.bundle-path }} | jq -c > MODULE.bazel.intoto.jsonl
        echo "MODULE_BAZEL_ATT_SHA_256=sha256-$(sha256sum MODULE.bazel.intoto.jsonl | awk '{print $1}' | xxd -r -p | base64)" >> $GITHUB_ENV

    - name: Create attestations.json
      run: envsubst < .templates/attestations.json.template > attestations.json

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          source.json
          MODULE.bazel
          ${{ env.ARCHIVE }}
          source.json.intoto.jsonl
          MODULE.bazel.intoto.jsonl
          ${{ env.ARCHIVE }}.intoto.jsonl
          attestations.json
          
